title = "Gitleaks Configuration for Farcaster MCP"

[extend]
useDefault = true


[[rules]]
id = "farcaster-fid"
description = "Detect hardcoded Farcaster FIDs that might be sensitive"
regex = '''(?i)(fid|follower_id|user_id)['"]?\s*[:=]\s*['"]?\d{4,}['"]?'''
tags = ["fid", "identifier"]

[[rules]]
id = "ethereum-private-key"
description = "Detect Ethereum private keys"
regex = '''0x[a-fA-F0-9]{64}'''
tags = ["key", "ethereum"]

[[rules]]
id = "api-endpoint-with-key"
description = "Detect API endpoints with embedded keys"
regex = '''https?://[^\s]*\?.*api[_-]?key=[^\s&]+'''
tags = ["api", "key"]

[allowlist]
paths = [
    "**/.gitleaks.toml",
    "**/go.sum",
    "**/package-lock.json",
    "**/yarn.lock",
    "**/uv.lock",
    "**/*.md"
]

# Allow test mnemonics (common test phrases)
regexes = [
    '''test test test test test test test test test test test junk''',
    '''abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about'''
]

# Rule-specific allowlists
[[rules]]
id = "mnemonic-seed-phrase-fixed"
description = "Detect potential mnemonic seed phrases with proper allowlist"
regex = '''(?i)(mnemonic|seed_phrase|seed|recovery_phrase)['"]?\s*[:=]\s*['"]?[a-z\s]{20,}['"]?'''
tags = ["key", "mnemonic", "seed"]
[rules.allowlist]
regexes = [
    '''MNEMONIC['"]?\s*[:=]\s*['"]?['"]?''',
    '''test test test'''
]